name: setup-flow
on:
  push:
    paths:
      - "src/scripts/**/*.py"
  workflow_dispatch:
defaults:
  run:
    working-directory: /app
jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: display the directory structure
        run: find .
  setup:
    runs-on: ubuntu-latest
    needs: [prep]
    steps:
      - uses: actions/checkout@v1
      - name: list everything
        run: |
          pwd
          find .
      - name: githup action to run setup
        run: |
          pwd
          /bin/bash -c ./run-fast.sh
      - name: notification
        env:
          slackurl: https://hooks.slack.com/services/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
        run: |
          ls -l /bin/messlack
          # curl -X POST -H 'Content-type: application/json' --data '{"text":"setup completed"}' $slackurl
  populateTables:
    runs-on: ubuntu-latest
    needs: [prep]
    steps:
      - uses: actions/checkout@v1
      - name: list everything
        run: |
          pwd
          find .
      - name: githup action to run setup
        run: |
          pwd
          /bin/bash -c ../src/scripts/shell/populateTables
      - name: message
        run: |
          echo "messtext=`/bin/date -R` datateamtest - populateTables completed" >> $GITHUB_ENV 
      - name: notification
        run: |
          echo curl -X POST -H Content-type: application/json --data {"text":"$messtext"} $SLACK_URL
  processTables:
    runs-on: ubuntu-latest
    needs: [prep]
    steps:
      - uses: actions/checkout@v1
      - name: list everything
        run: |
          pwd
          find .
      - name: githup action to run setup
        run: |
          pwd
          /bin/bash -c ../src/scripts/shell/processTables
      - name: message
        run: |
          echo "messtext=`/bin/date -R` datateamtest - processTables completed" >> $GITHUB_ENV 
      - name: notification
        run: |
          echo curl -X POST -H Content-type: application/json --data {"text":"$messtext"} $SLACK_URL
