name: setup-flow
on:
  push:
    paths:
      - "src/scripts/**/*.py"
  workflow_dispatch:
defaults:
  run:
    working-directory: ./space
jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: display the directory structure
        run: find .
  setup:
    runs-on: ubuntu-latest
    needs: [prep]
    steps:
      - uses: actions/checkout@v1
      - name: setup
        uses: actions/cache@v1
      - name: githup action to run setup
        run: |
          pwd
          ../src/scripts/shell/setup
